OUTDIR=$1
KERNELDIR=$2
PARAMJSON=$3
MAPCONSTRANTJSON=$4
SO=$5
BC=$6
mkdir -p $OUTDIR
cp -r $KERNELDIR $OUTDIR
cp $PARAMJSON $OUTDIR
cp $MAPCONSTRANTJSON $OUTDIR
cd $OUTDIR
opt-12 -load $SO -mapperPass $BC
